name: 'Maven build'
description: 'Checkout the source code and do a Maven build'
inputs:
  java-version:  # id of input
    description: 'JDK version'
    required: false
    default: '11'
  maven-params:  # id of input
    description: 'maven parameter'
    required: false
    default: ''
  token:  # id of input
    description: 'Github token'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup the JDK with caching for Maven
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: maven
        server-username: GITHUB_USER_REF  # env variable name for username
        server-password: GITHUB_TOKEN_REF # env variable name for GitHub Personal Access Token
    - name: Build with Maven
      run: mvn --batch-mode clean package ${{ inputs.maven-params }} --file pom.xml
      shell: bash
      env:
        GITHUB_USER_REF: 'mburton-crawfordtech'
        # GITHUB_USER_REF: ${{ secrets.GH_PACKAGE_REPO_USERNAME }}
        GITHUB_TOKEN_REF: ${{ inputs.token }}
