name: Java CI with Maven - deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Use the location in the repository (without action.yml)
    - name: Run custom action
      uses: mburton-crawfordtech/test_workflows@main
      
      # - name: Publish to GitHub Packages Apache Maven
        # run: mvn deploy 
        # run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        # env:
        #   GITHUB_TOKEN: ${{ github.token }}  