name: Java CI with Maven - deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: mburton-crawfordtech/test_workflows/.github/workflows/java-maven-build.yml@main
      
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy 
        # run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        # env:
        #   GITHUB_TOKEN: ${{ github.token }}  