name: Common Java CI with Maven - package

on:
  workflow_call:
    inputs:
      # pass in java version to allow different app requiring different java versions to 
      # reuse the same workflow, default to java 11
      java-version:
        required: false
        type: string
        default: '11'
      # working-directory is added to accommodate if the pom file is not in root.
      #  defaults to '.', current directory
      working-directory:
        required: false
        type: string
        default: '.'
      # allowing calling workflows to pass in maven parameter(s)
      # such as '-Dmaven.test.skip' for certain apps,
      # default to blank, not to skip test
      maven-params:
        required: false
        type: string
        default: ''
      # allowing calling workflows to pass in maven parameter(s)
      # such as '-Dmaven.test.skip' for certain apps,
      # default to blank, not to skip test
      token:
        required: false
        type: string
        default: ''

jobs:
  build:

    runs-on: ubuntu-latest

    # This sets the working directory at the job level,
    # defaults to "."
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
    - run: echo '${{ toJSON(github) }}'

    - name: Run custom action build action
      uses: mburton-crawfordtech/test_workflows/java-maven-build-action@main
      with:
        java-version: ${{ inputs.java-version }}
        maven-params: ${{ inputs.maven-params }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
      # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
